# Generated by Django 3.0.4 on 2020-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.AddField(
            model_name='contact',
            name='business_address',
            field=models.CharField(default=None, max_length=150, verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address',
            field=models.CharField(default=None, max_length=150, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(default=None, max_length=15, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(default=None, max_length=15, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone1',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone3',
            field=models.CharField(default=None, max_length=20, verbose_name='Phone 3'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default=None, max_length=15, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='E-mail Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=15, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default=None, max_length=20, verbose_name='Last Name'),
        ),
    ]
