# Generated by Django 3.0.4 on 2020-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200318_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='O', max_length=1, verbose_name='Gender'),
        ),
    ]
